name: CyansSimpleRaiding
version: '1.1.0'
main: cyansraiding.cyanssimpleraiding.CyansSimpleRaiding
api-version: '1.20'

commands:
  csr:
    description: Main command for Cyan's Simple Raiding plugin
    usage: /<command> [sub-command]
    aliases: [csrhelp, trust, untrust, toggle, admin]
  trust:
    description: Trust a player globally.
    usage: /trust <player>
  untrust:
    description: Untrust a player globally.
    usage: /untrust <player>
  csradmin:
    description: Toggle CSR admin mode.
    usage: /csradmin