name: CyansSimpleRaiding
version: '1.0'
main: cyansraiding.cyanssimpleraiding.CyansSimpleRaiding
api-version: '1.20'

commands:
  csradmin:
    description: Toggle CSR Admin mode to bypass chest health and permissions.
    usage: "/csradmin"